### ISSUE TITLE
Extra XML Generated

### ISSUE THREAD

**Issue by Gammer0909** [kasecato/vscode-docomment#137]
I've been using this extension for a while now, and I've been enjoying it a lot, it's very useful. However I am noticing one problem, sometimes when you type the `///`, it will generate two sets of XML for the same method/property/etc.

Eg.
```cs
/// <summary>
///
/// </summary>
/// <summary>
///
/// </summary>
public void Method() {

}
```

This isn't much a huge problem, as when you hit control + Z (cmd + Z on Mac) it will undo the second one, however it is an extra keystroke, and we developers hate that, you know! (Which is like, the entire reason for this extension...)

Thanks a lot!

**Comment by raphael-kahler** [comment]
I noticed the same. It seems to happen when you have both this extension and the [C#](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) extension enabled at the same time.

If you have only one of the two extension enabled then you get only one set of xml comments. With both extensions enabled you get two sets of comments.

I ended up disabling this extension and keeping just the C# extension enabled, since the C# extension is a requirement for other extensions like C# Dev Kit.

**Comment by Gammer0909** [comment]
> I ended up disabling this extension and keeping just the C# extension enabled, since the C# extension is a requirement for other extensions like C# Dev Kit.

Fair, I would like to see this bug fixed if possible though, as I didn't even know the C# Extension has auto-xml
